name: CI
on:
  push:
    branches:    
      - master
    tags:        
      - v*.*.*-beta.**
      - v*.*.**
    
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - uses: actions/checkout@v2
  
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: dev:prepare
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: publish --access=public
          auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
          registry-url: registry.npmjs.org
