name: CI
on:
  push:
    tags:
      - v*
      
env:
      # Access token for GitHub
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v2
  
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: dev:prepare
      - uses: borales/actions-yarn@v3.0.0
        with:
          cmd: publish --access=public
          auth-token: ${{ secrets.NPM_AUTH_TOKEN }}
          registry-url: registry.npmjs.org
